import { readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import sharp from 'sharp'

interface ImageEntry {
  path: string
  width: number
  height: number
}

const ASSETS_DIR = join(import.meta.dirname, '..', 'src', 'assets')
const OUTPUT = join(import.meta.dirname, '..', 'src', 'data', 'generatedImages.ts')
const EXT = /\.(jpg|jpeg|png|gif|webp|svg)$/i

async function getImages(dir: string, prefix = ''): Promise<ImageEntry[]> {
  const result: ImageEntry[] = []

  for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name),
  )) {
    const full = join(dir, entry.name)

    if (entry.isDirectory()) {
      result.push(...(await getImages(full, `${prefix}${entry.name}/`)))
    } else if (EXT.test(entry.name)) {
      const meta = await sharp(full).metadata()
      result.push({
        path: `${prefix}${entry.name}`,
        width: meta.width ?? 0,
        height: meta.height ?? 0,
      })
    }
  }

  return result
}

function esc(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

function pascalCase(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1)
}

function imageId(group: string, path: string): string {
  return `_img_${group}_${path.replace(/[^a-zA-Z0-9]/g, '_')}`
}

function importLine(id: string, path: string): string {
  return `import ${id} from '${esc(path)}?url'`
}

function imageLine(id: string, entry: ImageEntry): string {
  return `  image(${id}, ${entry.width}, ${entry.height}),`
}

function imageArray(name: string, entries: ImageEntry[], group: string): string {
  const lines = entries.map((entry) => imageLine(imageId(group, entry.path), entry))

  return `export const _${name}Urls: ProjectImage[] = [\n${lines.join('\n')}\n]\n`
}

async function main(): Promise<void> {
  const freelanceImages = await getImages(join(ASSETS_DIR, 'freelance3d'))
  const wallpaperImages = await getImages(join(ASSETS_DIR, 'wallpaper'))
  const subdirs = [...new Set(wallpaperImages.map((entry) => entry.path.split('/')[0]))].sort()

  const imports = [
    ...freelanceImages.map((entry) =>
      importLine(imageId('freelance3d', entry.path), `@/assets/freelance3d/${entry.path}`),
    ),
    ...wallpaperImages.map((entry) =>
      importLine(imageId('wallpaper', entry.path), `@/assets/wallpaper/${entry.path}`),
    ),
  ]

  const arrays = [
    imageArray('Freelance3d', freelanceImages, 'freelance3d'),
    ...subdirs.map((subdir) =>
      imageArray(
        pascalCase(subdir),
        wallpaperImages.filter((entry) => entry.path.startsWith(`${subdir}/`)),
        'wallpaper',
      ),
    ),
  ]

  const code = `// Auto-generated by scripts/update-image-dimensions.ts

import type { ProjectImage } from './portfolio'
${imports.join('\n')}

function image(src: string, width: number, height: number): ProjectImage {
  return { src, width, height }
}

${arrays.join('\n')}
`

  writeFileSync(OUTPUT, code, 'utf-8')
  console.log(`Generated ${OUTPUT}`)
}

await main()
