// Auto-generated by scripts/update-image-dimensions.ts

import type { ProjectImage } from './portfolio'
import _img_freelance3d_00_jpg from '@/assets/freelance3d/00.jpg?url'
import _img_freelance3d_01_jpg from '@/assets/freelance3d/01.jpg?url'
import _img_freelance3d_02_jpg from '@/assets/freelance3d/02.jpg?url'
import _img_freelance3d_03_jpg from '@/assets/freelance3d/03.jpg?url'
import _img_freelance3d_04_jpg from '@/assets/freelance3d/04.jpg?url'
import _img_freelance3d_05_jpg from '@/assets/freelance3d/05.jpg?url'
import _img_freelance3d_06_jpg from '@/assets/freelance3d/06.jpg?url'
import _img_freelance3d_07_jpg from '@/assets/freelance3d/07.jpg?url'
import _img_freelance3d_08_jpg from '@/assets/freelance3d/08.jpg?url'
import _img_freelance3d_09_jpg from '@/assets/freelance3d/09.jpg?url'
import _img_freelance3d_10_jpg from '@/assets/freelance3d/10.jpg?url'
import _img_freelance3d_11_jpg from '@/assets/freelance3d/11.jpg?url'
import _img_freelance3d_12_jpg from '@/assets/freelance3d/12.jpg?url'
import _img_freelance3d_13_jpg from '@/assets/freelance3d/13.jpg?url'
import _img_freelance3d_14_jpg from '@/assets/freelance3d/14.jpg?url'
import _img_freelance3d_15_jpg from '@/assets/freelance3d/15.jpg?url'
import _img_freelance3d_16_jpg from '@/assets/freelance3d/16.jpg?url'
import _img_freelance3d_17_jpg from '@/assets/freelance3d/17.jpg?url'
import _img_wallpaper_birds_birds_jpg from '@/assets/wallpaper/birds/birds.jpg?url'
import _img_wallpaper_chinoiserie_chinoiserie1_jpg from '@/assets/wallpaper/chinoiserie/chinoiserie1.jpg?url'
import _img_wallpaper_chinoiserie_chinoiserie2_jpg from '@/assets/wallpaper/chinoiserie/chinoiserie2.jpg?url'
import _img_wallpaper_chinoiserie_chinoiserie3_jpg from '@/assets/wallpaper/chinoiserie/chinoiserie3.jpg?url'
import _img_wallpaper_chinoiserie_chinoiserie4_jpg from '@/assets/wallpaper/chinoiserie/chinoiserie4.jpg?url'
import _img_wallpaper_forest_forest1_jpg from '@/assets/wallpaper/forest/forest1.jpg?url'
import _img_wallpaper_forest_forest2_jpg from '@/assets/wallpaper/forest/forest2.jpg?url'
import _img_wallpaper_forest_forest3_jpg from '@/assets/wallpaper/forest/forest3.jpg?url'
import _img_wallpaper_forest_forest4_jpg from '@/assets/wallpaper/forest/forest4.jpg?url'
import _img_wallpaper_llamaUnicorns_llamaUnicorns1_jpg from '@/assets/wallpaper/llamaUnicorns/llamaUnicorns1.jpg?url'
import _img_wallpaper_llamaUnicorns_llamaUnicorns2_jpg from '@/assets/wallpaper/llamaUnicorns/llamaUnicorns2.jpg?url'
import _img_wallpaper_llamaUnicorns_llamaUnicorns3_jpg from '@/assets/wallpaper/llamaUnicorns/llamaUnicorns3.jpg?url'
import _img_wallpaper_robo_robo1_png from '@/assets/wallpaper/robo/robo1.png?url'
import _img_wallpaper_robo_robo2_jpg from '@/assets/wallpaper/robo/robo2.jpg?url'
import _img_wallpaper_tropicalBirds_tropicalBirds1_jpg from '@/assets/wallpaper/tropicalBirds/tropicalBirds1.jpg?url'
import _img_wallpaper_tropicalBirds_tropicalBirds2_png from '@/assets/wallpaper/tropicalBirds/tropicalBirds2.png?url'
import _img_wallpaper_tropicalBirds_tropicalBirds3_jpg from '@/assets/wallpaper/tropicalBirds/tropicalBirds3.jpg?url'
import _img_wallpaper_tropicalBirds_tropicalBirds4_jpg from '@/assets/wallpaper/tropicalBirds/tropicalBirds4.jpg?url'
import _img_wallpaper_tropicalBirds_tropicalBirds5_jpg from '@/assets/wallpaper/tropicalBirds/tropicalBirds5.jpg?url'
import _img_wallpaper_tropics_tropics1_png from '@/assets/wallpaper/tropics/tropics1.png?url'
import _img_wallpaper_tropics_tropics2_jpg from '@/assets/wallpaper/tropics/tropics2.jpg?url'

function image(src: string, width: number, height: number): ProjectImage {
  return { src, width, height }
}

export const _Freelance3dUrls: ProjectImage[] = [
  image(_img_freelance3d_00_jpg, 1280, 1280),
  image(_img_freelance3d_01_jpg, 1200, 1200),
  image(_img_freelance3d_02_jpg, 1200, 1200),
  image(_img_freelance3d_03_jpg, 1200, 1200),
  image(_img_freelance3d_04_jpg, 1200, 1200),
  image(_img_freelance3d_05_jpg, 1505, 1804),
  image(_img_freelance3d_06_jpg, 1536, 1443),
  image(_img_freelance3d_07_jpg, 1478, 1189),
  image(_img_freelance3d_08_jpg, 1338, 962),
  image(_img_freelance3d_09_jpg, 978, 955),
  image(_img_freelance3d_10_jpg, 1324, 948),
  image(_img_freelance3d_11_jpg, 833, 593),
  image(_img_freelance3d_12_jpg, 1280, 1280),
  image(_img_freelance3d_13_jpg, 1280, 1280),
  image(_img_freelance3d_14_jpg, 1280, 1280),
  image(_img_freelance3d_15_jpg, 1280, 1280),
  image(_img_freelance3d_16_jpg, 1200, 1200),
  image(_img_freelance3d_17_jpg, 1200, 1200),
]

export const _BirdsUrls: ProjectImage[] = [
  image(_img_wallpaper_birds_birds_jpg, 1920, 1280),
]

export const _ChinoiserieUrls: ProjectImage[] = [
  image(_img_wallpaper_chinoiserie_chinoiserie1_jpg, 3190, 3150),
  image(_img_wallpaper_chinoiserie_chinoiserie2_jpg, 4000, 2666),
  image(_img_wallpaper_chinoiserie_chinoiserie3_jpg, 2835, 2232),
  image(_img_wallpaper_chinoiserie_chinoiserie4_jpg, 1280, 782),
]

export const _ForestUrls: ProjectImage[] = [
  image(_img_wallpaper_forest_forest1_jpg, 5906, 4005),
  image(_img_wallpaper_forest_forest2_jpg, 700, 420),
  image(_img_wallpaper_forest_forest3_jpg, 5906, 2215),
  image(_img_wallpaper_forest_forest4_jpg, 3300, 2732),
]

export const _LlamaUnicornsUrls: ProjectImage[] = [
  image(_img_wallpaper_llamaUnicorns_llamaUnicorns1_jpg, 3011, 2700),
  image(_img_wallpaper_llamaUnicorns_llamaUnicorns2_jpg, 3000, 2000),
  image(_img_wallpaper_llamaUnicorns_llamaUnicorns3_jpg, 2835, 2430),
]

export const _RoboUrls: ProjectImage[] = [
  image(_img_wallpaper_robo_robo1_png, 1448, 1086),
  image(_img_wallpaper_robo_robo2_jpg, 2734, 5906),
]

export const _TropicalBirdsUrls: ProjectImage[] = [
  image(_img_wallpaper_tropicalBirds_tropicalBirds1_jpg, 531, 740),
  image(_img_wallpaper_tropicalBirds_tropicalBirds2_png, 1198, 1313),
  image(_img_wallpaper_tropicalBirds_tropicalBirds3_jpg, 962, 902),
  image(_img_wallpaper_tropicalBirds_tropicalBirds4_jpg, 836, 901),
  image(_img_wallpaper_tropicalBirds_tropicalBirds5_jpg, 952, 903),
]

export const _TropicsUrls: ProjectImage[] = [
  image(_img_wallpaper_tropics_tropics1_png, 1448, 1086),
  image(_img_wallpaper_tropics_tropics2_jpg, 5906, 2307),
]

