// Auto-generated by scripts/update-image-dimensions.ts

import type { ProjectImage } from './portfolio'
import _img_freelance3d_00_preview_webp_1kk4wbz from '@/assets/freelance3d/00-preview.webp?url'
import _img_freelance3d_01_preview_webp_1c750su from '@/assets/freelance3d/01-preview.webp?url'
import _img_freelance3d_02_preview_webp_13u559p from '@/assets/freelance3d/02-preview.webp?url'
import _img_freelance3d_03_preview_webp_vh59qk from '@/assets/freelance3d/03-preview.webp?url'
import _img_freelance3d_04_preview_webp_n45e7f from '@/assets/freelance3d/04-preview.webp?url'
import _img_freelance3d_05_preview_webp_er5ioa from '@/assets/freelance3d/05-preview.webp?url'
import _img_freelance3d_06_preview_webp_6e5n55 from '@/assets/freelance3d/06-preview.webp?url'
import _img_freelance3d_07_preview_webp_1x29tl4 from '@/assets/freelance3d/07-preview.webp?url'
import _img_freelance3d_08_preview_webp_1op9y1z from '@/assets/freelance3d/08-preview.webp?url'
import _img_freelance3d_09_preview_webp_1gca2iu from '@/assets/freelance3d/09-preview.webp?url'
import _img_freelance3d_10_preview_webp_agkws0 from '@/assets/freelance3d/10-preview.webp?url'
import _img_freelance3d_11_preview_webp_23l18v from '@/assets/freelance3d/11-preview.webp?url'
import _img_freelance3d_12_preview_webp_1srp7ou from '@/assets/freelance3d/12-preview.webp?url'
import _img_freelance3d_13_preview_webp_1kepc5p from '@/assets/freelance3d/13-preview.webp?url'
import _img_freelance3d_14_preview_webp_1c1pgmk from '@/assets/freelance3d/14-preview.webp?url'
import _img_freelance3d_15_preview_webp_13opl3f from '@/assets/freelance3d/15-preview.webp?url'
import _img_freelance3d_16_preview_webp_vbppka from '@/assets/freelance3d/16-preview.webp?url'
import _img_freelance3d_17_preview_webp_mypu15 from '@/assets/freelance3d/17-preview.webp?url'
import _img_wallpaper_birds_birds_preview_webp_yg55ka from '@/assets/wallpaper/birds/birds-preview.webp?url'
import _img_wallpaper_chinoiserie_chinoiserie1_preview_webp_o3r5vj from '@/assets/wallpaper/chinoiserie/chinoiserie1-preview.webp?url'
import _img_wallpaper_chinoiserie_chinoiserie2_preview_webp_fqrace from '@/assets/wallpaper/chinoiserie/chinoiserie2-preview.webp?url'
import _img_wallpaper_chinoiserie_chinoiserie3_preview_webp_7dret9 from '@/assets/wallpaper/chinoiserie/chinoiserie3-preview.webp?url'
import _img_wallpaper_chinoiserie_chinoiserie4_preview_webp_1y1vl98 from '@/assets/wallpaper/chinoiserie/chinoiserie4-preview.webp?url'
import _img_wallpaper_forest_forest1_preview_webp_g81sfh from '@/assets/wallpaper/forest/forest1-preview.webp?url'
import _img_wallpaper_forest_forest2_preview_webp_7v1wwc from '@/assets/wallpaper/forest/forest2-preview.webp?url'
import _img_wallpaper_forest_forest3_preview_webp_1yj63cb from '@/assets/wallpaper/forest/forest3-preview.webp?url'
import _img_wallpaper_forest_forest4_preview_webp_1q667t6 from '@/assets/wallpaper/forest/forest4-preview.webp?url'
import _img_wallpaper_llamaUnicorns_llamaUnicorns1_preview_webp_u5tfjj from '@/assets/wallpaper/llamaUnicorns/llamaUnicorns1-preview.webp?url'
import _img_wallpaper_llamaUnicorns_llamaUnicorns2_preview_webp_lstk0e from '@/assets/wallpaper/llamaUnicorns/llamaUnicorns2-preview.webp?url'
import _img_wallpaper_llamaUnicorns_llamaUnicorns3_preview_webp_dftoh9 from '@/assets/wallpaper/llamaUnicorns/llamaUnicorns3-preview.webp?url'
import _img_wallpaper_robo_robo1_preview_webp_2kb5xp from '@/assets/wallpaper/robo/robo1-preview.webp?url'
import _img_wallpaper_robo_robo2_preview_webp_1t8fcdo from '@/assets/wallpaper/robo/robo2-preview.webp?url'
import _img_wallpaper_tropicalBirds_tropicalBirds1_preview_webp_1ornq63 from '@/assets/wallpaper/tropicalBirds/tropicalBirds1-preview.webp?url'
import _img_wallpaper_tropicalBirds_tropicalBirds2_preview_webp_1genumy from '@/assets/wallpaper/tropicalBirds/tropicalBirds2-preview.webp?url'
import _img_wallpaper_tropicalBirds_tropicalBirds3_preview_webp_181nz3t from '@/assets/wallpaper/tropicalBirds/tropicalBirds3-preview.webp?url'
import _img_wallpaper_tropicalBirds_tropicalBirds4_preview_webp_zoo3ko from '@/assets/wallpaper/tropicalBirds/tropicalBirds4-preview.webp?url'
import _img_wallpaper_tropicalBirds_tropicalBirds5_preview_webp_rbo81j from '@/assets/wallpaper/tropicalBirds/tropicalBirds5-preview.webp?url'
import _img_wallpaper_tropics_tropics1_preview_webp_1pc1nur from '@/assets/wallpaper/tropics/tropics1-preview.webp?url'
import _img_wallpaper_tropics_tropics2_preview_webp_1gz1sbm from '@/assets/wallpaper/tropics/tropics2-preview.webp?url'
import _img_otherProjects_art_00_preview_webp_fuj01v from '@/assets/otherProjects/art/00-preview.webp?url'
import _img_otherProjects_art_01_preview_webp_7hj4iq from '@/assets/otherProjects/art/01-preview.webp?url'
import _img_otherProjects_art_02_preview_webp_1y5nayp from '@/assets/otherProjects/art/02-preview.webp?url'
import _img_otherProjects_art_03_preview_webp_1psnffk from '@/assets/otherProjects/art/03-preview.webp?url'
import _img_otherProjects_art_04_preview_webp_1hfnjwf from '@/assets/otherProjects/art/04-preview.webp?url'
import _img_otherProjects_art_05_preview_webp_192noda from '@/assets/otherProjects/art/05-preview.webp?url'
import _img_otherProjects_art_06_preview_webp_10pnsu5 from '@/assets/otherProjects/art/06-preview.webp?url'
import _img_otherProjects_art_07_preview_webp_scnxb0 from '@/assets/otherProjects/art/07-preview.webp?url'
import _img_otherProjects_art_08_preview_webp_jzo1rv from '@/assets/otherProjects/art/08-preview.webp?url'
import _img_otherProjects_art_09_preview_webp_bmo68q from '@/assets/otherProjects/art/09-preview.webp?url'
import _img_otherProjects_art_10_preview_webp_14s32h0 from '@/assets/otherProjects/art/10-preview.webp?url'
import _img_otherProjects_studentWork_3dMax_____________preview_webp_16sc3nj from '@/assets/otherProjects/studentWork/3dMax/Главный вид-preview.webp?url'
import _img_otherProjects_studentWork_3dMax________1_preview_webp_1jhbaac from '@/assets/otherProjects/studentWork/3dMax/Доп.вид1-preview.webp?url'
import _img_otherProjects_studentWork_3dMax________2_preview_webp_1b4ber7 from '@/assets/otherProjects/studentWork/3dMax/Доп.вид2-preview.webp?url'
import _img_otherProjects_studentWork_3dMax____________________1_preview_webp_owk913 from '@/assets/otherProjects/studentWork/3dMax/Дополнительный вид 1-preview.webp?url'
import _img_otherProjects_studentWork_3dMax____________________2_preview_webp_gjkdhy from '@/assets/otherProjects/studentWork/3dMax/Дополнительный вид 2-preview.webp?url'
import _img_otherProjects_studentWork_3dMax____________preview_webp_1koanl from '@/assets/otherProjects/studentWork/3dMax/Инсталяция-preview.webp?url'
import _img_otherProjects_studentWork_3dMax______preview_webp_1mg1ui1 from '@/assets/otherProjects/studentWork/3dMax/Кафе-preview.webp?url'
import _img_otherProjects_studentWork_3dMax_______preview_webp_jpcsyz from '@/assets/otherProjects/studentWork/3dMax/Сцена-preview.webp?url'
import _img_otherProjects_studentWork_3dMax______preview_webp_1i4fhp4 from '@/assets/otherProjects/studentWork/3dMax/Тент-preview.webp?url'
import _img_otherProjects_studentWork_blender________preview_webp_seik6u from '@/assets/otherProjects/studentWork/blender/стадии-preview.webp?url'
import _img_otherProjects_studentWork_graphics_1845_preview_webp_182qzwm from '@/assets/otherProjects/studentWork/graphics/1845-preview.webp?url'
import _img_otherProjects_studentWork_graphics_5ePDINeDxjI_preview_webp_1l9o7k1 from '@/assets/otherProjects/studentWork/graphics/5ePDINeDxjI-preview.webp?url'
import _img_otherProjects_studentWork_graphics_Bq7_ItMiucI_preview_webp_1u4nc4z from '@/assets/otherProjects/studentWork/graphics/Bq7_ItMiucI-preview.webp?url'
import _img_otherProjects_studentWork_graphics_cuFHlFBDWlw_preview_webp_hcyibi from '@/assets/otherProjects/studentWork/graphics/cuFHlFBDWlw-preview.webp?url'
import _img_otherProjects_studentWork_graphics_DRITAIkZYM8_preview_webp_1wk704c from '@/assets/otherProjects/studentWork/graphics/DRITAIkZYM8-preview.webp?url'
import _img_otherProjects_studentWork_graphics_ej686d2CnQc_preview_webp_17md57a from '@/assets/otherProjects/studentWork/graphics/ej686d2CnQc-preview.webp?url'
import _img_otherProjects_studentWork_graphics_gFwlvPpdsv0_preview_webp_7hzgh1 from '@/assets/otherProjects/studentWork/graphics/gFwlvPpdsv0-preview.webp?url'
import _img_otherProjects_studentWork_graphics_nADpRxMnYnA_preview_webp_4kftu2 from '@/assets/otherProjects/studentWork/graphics/nADpRxMnYnA-preview.webp?url'
import _img_otherProjects_studentWork_graphics_rxTPjeELpkM_preview_webp_c4oyma from '@/assets/otherProjects/studentWork/graphics/rxTPjeELpkM-preview.webp?url'
import _img_otherProjects_studentWork_graphics_uVCT4qGiaW0_preview_webp_boav3b from '@/assets/otherProjects/studentWork/graphics/uVCT4qGiaW0-preview.webp?url'
import _img_otherProjects_studentWork_painting_1_preview_webp_15x9qjq from '@/assets/otherProjects/studentWork/painting/1-preview.webp?url'
import _img_otherProjects_studentWork_painting_2_preview_webp_xk9v0l from '@/assets/otherProjects/studentWork/painting/2-preview.webp?url'
import _img_otherProjects_studentWork_painting_4_preview_webp_gua3yb from '@/assets/otherProjects/studentWork/painting/4-preview.webp?url'
import _img_otherProjects_studentWork_painting_6_preview_webp_4acw1 from '@/assets/otherProjects/studentWork/painting/6-preview.webp?url'
import _img_otherProjects_studentWork_painting_7_preview_webp_1qsejc0 from '@/assets/otherProjects/studentWork/painting/7-preview.webp?url'
import _img_otherProjects_studentWork_painting_8_preview_webp_1ifensv from '@/assets/otherProjects/studentWork/painting/8-preview.webp?url'
import _img_otherProjects_studentWork_painting_9_preview_webp_1a2es9q from '@/assets/otherProjects/studentWork/painting/9-preview.webp?url'
import _img_signs_operatingMode_1_1_preview_webp_1usz99i from '@/assets/signs/operatingMode/1.1-preview.webp?url'
import _img_signs_operatingMode_1_2_preview_webp_1mfzdqd from '@/assets/signs/operatingMode/1.2-preview.webp?url'
import _img_signs_operatingMode_3_preview_webp_1b70rwn from '@/assets/signs/operatingMode/3-preview.webp?url'
import _img_signs_operatingMode_3_3_preview_webp_x72gte from '@/assets/signs/operatingMode/3.3-preview.webp?url'
import _img_signs_operatingMode_4_1_preview_webp_15h3p6r from '@/assets/signs/operatingMode/4.1-preview.webp?url'
import _img_signs_operatingMode_4_2_preview_webp_x43tnm from '@/assets/signs/operatingMode/4.2-preview.webp?url'
import _img_signs_operatingMode_image_2026_06_04_00_09_45_preview_webp_1pk6tif from '@/assets/signs/operatingMode/image_2026-06-04_00-09-45-preview.webp?url'
import _img_signs_operatingMode_photo_2026_07_08_18_19_46__5__preview_webp_16xhige from '@/assets/signs/operatingMode/photo_2026-07-08_18-19-46 (5)-preview.webp?url'
import _img_signs_operatingMode_photo_2026_07_08_18_19_47__3__preview_webp_1blupmz from '@/assets/signs/operatingMode/photo_2026-07-08_18-19-47 (3)-preview.webp?url'
import _img_signs_operatingMode_photo_2026_07_08_18_19_47_preview_webp_6z2zft from '@/assets/signs/operatingMode/photo_2026-07-08_18-19-47-preview.webp?url'
import _img_signs_qr_image_2026_06_03_12_33_50_preview_webp_13jqf51 from '@/assets/signs/qr/image_2026-06-03_12-33-50-preview.webp?url'
import _img_signs_qr_photo_2026_07_08_18_19_47__2__preview_webp_q89he5 from '@/assets/signs/qr/photo_2026-07-08_18-19-47 (2)-preview.webp?url'
import _img_signs_qr_photo_2026_07_08_18_19_47__4__preview_webp_529k9b from '@/assets/signs/qr/photo_2026-07-08_18-19-47 (4)-preview.webp?url'
import _img_signs_signs_2_1_preview_webp_m0imer from '@/assets/signs/signs/2.1-preview.webp?url'
import _img_signs_signs_2_2_preview_webp_dniqvm from '@/assets/signs/signs/2.2-preview.webp?url'
import _img_signs_signs_2_3_preview_webp_5aivch from '@/assets/signs/signs/2.3-preview.webp?url'
import _img_signs_signs_image_2026_05_29_13_13_09_preview_webp_58etbc from '@/assets/signs/signs/image_2026-05-29_13-13-09-preview.webp?url'
import _img_signs_signs_image_2026_06_03_16_41_18_preview_webp_gbeg2l from '@/assets/signs/signs/image_2026-06-03_16-41-18-preview.webp?url'
import _img_signs_signs_image_2026_06_04_00_09_57_preview_webp_vywk4 from '@/assets/signs/signs/image_2026-06-04_00-09-57-preview.webp?url'
import _img_card_bowl_Bowl1_preview_webp_m5fp4d from '@/assets/card/bowl/Bowl1-preview.webp?url'
import _img_card_bowl_Bowl2_preview_webp_dsftl8 from '@/assets/card/bowl/Bowl2-preview.webp?url'
import _img_card_bowl_Bowl3_preview_webp_5ffy23 from '@/assets/card/bowl/Bowl3-preview.webp?url'
import _img_card_bowl_Bowl4_preview_webp_1w3k4i2 from '@/assets/card/bowl/Bowl4-preview.webp?url'
import _img_card_bowl_Bowl5_preview_webp_1nqk8yx from '@/assets/card/bowl/Bowl5-preview.webp?url'
import _img_card_bowl_Bowl6_preview_webp_1fdkdfs from '@/assets/card/bowl/Bowl6-preview.webp?url'
import _img_card_glasses_Glasses1_preview_webp_x6m8hv from '@/assets/card/glasses/Glasses1-preview.webp?url'
import _img_card_glasses_Glasses2_preview_webp_otmcyq from '@/assets/card/glasses/Glasses2-preview.webp?url'
import _img_card_glasses_Glasses3_preview_webp_ggmhfl from '@/assets/card/glasses/Glasses3-preview.webp?url'
import _img_card_glasses_Glasses4_preview_webp_83mlwg from '@/assets/card/glasses/Glasses4-preview.webp?url'
import _img_card_glasses_Glasses5_preview_webp_1yrqscf from '@/assets/card/glasses/Glasses5-preview.webp?url'
import _img_card_glasses_Glasses6_preview_webp_1qeqwta from '@/assets/card/glasses/Glasses6-preview.webp?url'
import _img_freelance3d_full_00_full_webp_1rxwob2 from '@/assets/freelance3d/00-full.webp?url'
import _img_freelance3d_full_01_full_webp_y81rrj from '@/assets/freelance3d/01-full.webp?url'
import _img_freelance3d_full_02_full_webp_4i6v80 from '@/assets/freelance3d/02-full.webp?url'
import _img_freelance3d_full_03_full_webp_19tg0nl from '@/assets/freelance3d/03-full.webp?url'
import _img_freelance3d_full_04_full_webp_g3l442 from '@/assets/freelance3d/04-full.webp?url'
import _img_freelance3d_full_05_full_webp_1leu9jn from '@/assets/freelance3d/05-full.webp?url'
import _img_freelance3d_full_06_full_webp_rozd04 from '@/assets/freelance3d/06-full.webp?url'
import _img_freelance3d_full_07_full_webp_1x08ifp from '@/assets/freelance3d/07-full.webp?url'
import _img_freelance3d_full_08_full_webp_13adlw6 from '@/assets/freelance3d/08-full.webp?url'
import _img_freelance3d_full_09_full_webp_9kipcn from '@/assets/freelance3d/09-full.webp?url'
import _img_freelance3d_full_10_full_webp_1u2rd65 from '@/assets/freelance3d/10-full.webp?url'
import _img_freelance3d_full_11_full_webp_10cwgmm from '@/assets/freelance3d/11-full.webp?url'
import _img_freelance3d_full_12_full_webp_6n1k33 from '@/assets/freelance3d/12-full.webp?url'
import _img_freelance3d_full_13_full_webp_1byapio from '@/assets/freelance3d/13-full.webp?url'
import _img_freelance3d_full_14_full_webp_i8fsz5 from '@/assets/freelance3d/14-full.webp?url'
import _img_freelance3d_full_15_full_webp_1njoyeq from '@/assets/freelance3d/15-full.webp?url'
import _img_freelance3d_full_16_full_webp_ttu1v7 from '@/assets/freelance3d/16-full.webp?url'
import _img_freelance3d_full_17_full_webp_3z5bo from '@/assets/freelance3d/17-full.webp?url'
import _img_wallpaper_full_birds_birds_full_webp_11m9f77 from '@/assets/wallpaper/birds/birds-full.webp?url'
import _img_wallpaper_full_chinoiserie_chinoiserie1_full_webp_1m68egu from '@/assets/wallpaper/chinoiserie/chinoiserie1-full.webp?url'
import _img_wallpaper_full_chinoiserie_chinoiserie2_full_webp_sgdhxb from '@/assets/wallpaper/chinoiserie/chinoiserie2-full.webp?url'
import _img_wallpaper_full_chinoiserie_chinoiserie3_full_webp_1xrmncw from '@/assets/wallpaper/chinoiserie/chinoiserie3-full.webp?url'
import _img_wallpaper_full_chinoiserie_chinoiserie4_full_webp_141rqtd from '@/assets/wallpaper/chinoiserie/chinoiserie4-full.webp?url'
import _img_wallpaper_full_forest_forest1_full_webp_11iw47k from '@/assets/wallpaper/forest/forest1-full.webp?url'
import _img_wallpaper_full_forest_forest2_full_webp_7t17o1 from '@/assets/wallpaper/forest/forest2-full.webp?url'
import _img_wallpaper_full_forest_forest3_full_webp_1d4ad3m from '@/assets/wallpaper/forest/forest3-full.webp?url'
import _img_wallpaper_full_forest_forest4_full_webp_jefgk3 from '@/assets/wallpaper/forest/forest4-full.webp?url'
import _img_wallpaper_full_llamaUnicorns_llamaUnicorns1_full_webp_1bwt1am from '@/assets/wallpaper/llamaUnicorns/llamaUnicorns1-full.webp?url'
import _img_wallpaper_full_llamaUnicorns_llamaUnicorns2_full_webp_i6y4r3 from '@/assets/wallpaper/llamaUnicorns/llamaUnicorns2-full.webp?url'
import _img_wallpaper_full_llamaUnicorns_llamaUnicorns3_full_webp_1ni7a6o from '@/assets/wallpaper/llamaUnicorns/llamaUnicorns3-full.webp?url'
import _img_wallpaper_full_robo_robo1_full_webp_15zh12o from '@/assets/wallpaper/robo/robo1-full.webp?url'
import _img_wallpaper_full_robo_robo2_full_webp_c9m4j5 from '@/assets/wallpaper/robo/robo2-full.webp?url'
import _img_wallpaper_full_tropicalBirds_tropicalBirds1_full_webp_18zv7ya from '@/assets/wallpaper/tropicalBirds/tropicalBirds1-full.webp?url'
import _img_wallpaper_full_tropicalBirds_tropicalBirds2_full_webp_fa0ber from '@/assets/wallpaper/tropicalBirds/tropicalBirds2-full.webp?url'
import _img_wallpaper_full_tropicalBirds_tropicalBirds3_full_webp_1kl9guc from '@/assets/wallpaper/tropicalBirds/tropicalBirds3-full.webp?url'
import _img_wallpaper_full_tropicalBirds_tropicalBirds4_full_webp_qvekat from '@/assets/wallpaper/tropicalBirds/tropicalBirds4-full.webp?url'
import _img_wallpaper_full_tropicalBirds_tropicalBirds5_full_webp_1w6npqe from '@/assets/wallpaper/tropicalBirds/tropicalBirds5-full.webp?url'
import _img_wallpaper_full_tropics_tropics1_full_webp_1ivtqgq from '@/assets/wallpaper/tropics/tropics1-full.webp?url'
import _img_wallpaper_full_tropics_tropics2_full_webp_p5ytx7 from '@/assets/wallpaper/tropics/tropics2-full.webp?url'
import _img_otherProjects_full_art_00_full_webp_10wbewq from '@/assets/otherProjects/art/00-full.webp?url'
import _img_otherProjects_full_art_01_full_webp_76gid7 from '@/assets/otherProjects/art/01-full.webp?url'
import _img_otherProjects_full_art_02_full_webp_1chpnss from '@/assets/otherProjects/art/02-full.webp?url'
import _img_otherProjects_full_art_03_full_webp_irur99 from '@/assets/otherProjects/art/03-full.webp?url'
import _img_otherProjects_full_art_04_full_webp_1o33wou from '@/assets/otherProjects/art/04-full.webp?url'
import _img_otherProjects_full_art_05_full_webp_ud905b from '@/assets/otherProjects/art/05-full.webp?url'
import _img_otherProjects_full_art_06_full_webp_ne3ls from '@/assets/otherProjects/art/06-full.webp?url'
import _img_otherProjects_full_art_07_full_webp_15yn91d from '@/assets/otherProjects/art/07-full.webp?url'
import _img_otherProjects_full_art_08_full_webp_c8schu from '@/assets/otherProjects/art/08-full.webp?url'
import _img_otherProjects_full_art_09_full_webp_1hk1hxf from '@/assets/otherProjects/art/09-full.webp?url'
import _img_otherProjects_full_art_10_full_webp_13163rt from '@/assets/otherProjects/art/10-full.webp?url'
import _img_otherProjects_full_studentWork_3dMax_____________full_webp_9amxj2 from '@/assets/otherProjects/studentWork/3dMax/Главный вид-full.webp?url'
import _img_otherProjects_full_studentWork_3dMax________1_full_webp_1arpzwp from '@/assets/otherProjects/studentWork/3dMax/Доп.вид1-full.webp?url'
import _img_otherProjects_full_studentWork_3dMax________2_full_webp_h1v3d6 from '@/assets/otherProjects/studentWork/3dMax/Доп.вид2-full.webp?url'
import _img_otherProjects_full_studentWork_3dMax____________________1_full_webp_1639ypy from '@/assets/otherProjects/studentWork/3dMax/Дополнительный вид 1-full.webp?url'
import _img_otherProjects_full_studentWork_3dMax____________________2_full_webp_cdf26f from '@/assets/otherProjects/studentWork/3dMax/Дополнительный вид 2-full.webp?url'
import _img_otherProjects_full_studentWork_3dMax____________full_webp_lcheks from '@/assets/otherProjects/studentWork/3dMax/Инсталяция-full.webp?url'
import _img_otherProjects_full_studentWork_3dMax______full_webp_1ce9jro from '@/assets/otherProjects/studentWork/3dMax/Кафе-full.webp?url'
import _img_otherProjects_full_studentWork_3dMax_______full_webp_12jdjma from '@/assets/otherProjects/studentWork/3dMax/Сцена-full.webp?url'
import _img_otherProjects_full_studentWork_3dMax______full_webp_1h6j479 from '@/assets/otherProjects/studentWork/3dMax/Тент-full.webp?url'
import _img_otherProjects_full_studentWork_blender________full_webp_1jnokmf from '@/assets/otherProjects/studentWork/blender/стадии-full.webp?url'
import _img_otherProjects_full_studentWork_graphics_1845_full_webp_li774n from '@/assets/otherProjects/studentWork/graphics/1845-full.webp?url'
import _img_otherProjects_full_studentWork_graphics_5ePDINeDxjI_full_webp_ghpdbw from '@/assets/otherProjects/studentWork/graphics/5ePDINeDxjI-full.webp?url'
import _img_otherProjects_full_studentWork_graphics_Bq7_ItMiucI_full_webp_5clw5m from '@/assets/otherProjects/studentWork/graphics/Bq7_ItMiucI-full.webp?url'
import _img_otherProjects_full_studentWork_graphics_cuFHlFBDWlw_full_webp_1iwz2zj from '@/assets/otherProjects/studentWork/graphics/cuFHlFBDWlw-full.webp?url'
import _img_otherProjects_full_studentWork_graphics_DRITAIkZYM8_full_webp_ro0zgh from '@/assets/otherProjects/studentWork/graphics/DRITAIkZYM8-full.webp?url'
import _img_otherProjects_full_studentWork_graphics_ej686d2CnQc_full_webp_1cmhjt3 from '@/assets/otherProjects/studentWork/graphics/ej686d2CnQc-full.webp?url'
import _img_otherProjects_full_studentWork_graphics_gFwlvPpdsv0_full_webp_1qzxys8 from '@/assets/otherProjects/studentWork/graphics/gFwlvPpdsv0-full.webp?url'
import _img_otherProjects_full_studentWork_graphics_nADpRxMnYnA_full_webp_1bj4loz from '@/assets/otherProjects/studentWork/graphics/nADpRxMnYnA-full.webp?url'
import _img_otherProjects_full_studentWork_graphics_rxTPjeELpkM_full_webp_hi1lcr from '@/assets/otherProjects/studentWork/graphics/rxTPjeELpkM-full.webp?url'
import _img_otherProjects_full_studentWork_graphics_uVCT4qGiaW0_full_webp_vtwul2 from '@/assets/otherProjects/studentWork/graphics/uVCT4qGiaW0-full.webp?url'
import _img_otherProjects_full_studentWork_painting_1_full_webp_uka92v from '@/assets/otherProjects/studentWork/painting/1-full.webp?url'
import _img_otherProjects_full_studentWork_painting_2_full_webp_ufcjc from '@/assets/otherProjects/studentWork/painting/2-full.webp?url'
import _img_otherProjects_full_studentWork_painting_4_full_webp_cftlfe from '@/assets/otherProjects/studentWork/painting/4-full.webp?url'
import _img_otherProjects_full_studentWork_painting_6_full_webp_o17ubg from '@/assets/otherProjects/studentWork/painting/6-full.webp?url'
import _img_otherProjects_full_studentWork_painting_7_full_webp_1tcgzr1 from '@/assets/otherProjects/studentWork/painting/7-full.webp?url'
import _img_otherProjects_full_studentWork_painting_8_full_webp_zmm37i from '@/assets/otherProjects/studentWork/painting/8-full.webp?url'
import _img_otherProjects_full_studentWork_painting_9_full_webp_5wr6nz from '@/assets/otherProjects/studentWork/painting/9-full.webp?url'
import _img_signs_full_operatingMode_1_1_full_webp_1hk3wc7 from '@/assets/signs/operatingMode/1.1-full.webp?url'
import _img_signs_full_operatingMode_1_2_full_webp_nu8zso from '@/assets/signs/operatingMode/1.2-full.webp?url'
import _img_signs_full_operatingMode_3_full_webp_zps3ue from '@/assets/signs/operatingMode/3-full.webp?url'
import _img_signs_full_operatingMode_3_3_full_webp_1jg4ut7 from '@/assets/signs/operatingMode/3.3-full.webp?url'
import _img_signs_full_operatingMode_4_1_full_webp_1301ypm from '@/assets/signs/operatingMode/4.1-full.webp?url'
import _img_signs_full_operatingMode_4_2_full_webp_9a7263 from '@/assets/signs/operatingMode/4.2-full.webp?url'
import _img_signs_full_operatingMode_image_2026_06_04_00_09_45_full_webp_nhmw2e from '@/assets/signs/operatingMode/image_2026-06-04_00-09-45-full.webp?url'
import _img_signs_full_operatingMode_photo_2026_07_08_18_19_46__5__full_webp_18u0bjj from '@/assets/signs/operatingMode/photo_2026-07-08_18-19-46 (5)-full.webp?url'
import _img_signs_full_operatingMode_photo_2026_07_08_18_19_47__3__full_webp_1thv08i from '@/assets/signs/operatingMode/photo_2026-07-08_18-19-47 (3)-full.webp?url'
import _img_signs_full_operatingMode_photo_2026_07_08_18_19_47_full_webp_jkpq1g from '@/assets/signs/operatingMode/photo_2026-07-08_18-19-47-full.webp?url'
import _img_signs_full_qr_image_2026_06_03_12_33_50_full_webp_1411p3s from '@/assets/signs/qr/image_2026-06-03_12-33-50-full.webp?url'
import _img_signs_full_qr_photo_2026_07_08_18_19_47__2__full_webp_1evx9gw from '@/assets/signs/qr/photo_2026-07-08_18-19-47 (2)-full.webp?url'
import _img_signs_full_qr_photo_2026_07_08_18_19_47__4__full_webp_1j5mn72 from '@/assets/signs/qr/photo_2026-07-08_18-19-47 (4)-full.webp?url'
import _img_signs_full_signs_2_1_full_webp_gfloay from '@/assets/signs/signs/2.1-full.webp?url'
import _img_signs_full_signs_2_2_full_webp_1lqutqj from '@/assets/signs/signs/2.2-full.webp?url'
import _img_signs_full_signs_2_3_full_webp_s0zx70 from '@/assets/signs/signs/2.3-full.webp?url'
import _img_signs_full_signs_image_2026_05_29_13_13_09_full_webp_eya0l1 from '@/assets/signs/signs/image_2026-05-29_13-13-09-full.webp?url'
import _img_signs_full_signs_image_2026_06_03_16_41_18_full_webp_1ajck2o from '@/assets/signs/signs/image_2026-06-03_16-41-18-full.webp?url'
import _img_signs_full_signs_image_2026_06_04_00_09_57_full_webp_6pmkjt from '@/assets/signs/signs/image_2026-06-04_00-09-57-full.webp?url'
import _img_card_full_bowl_Bowl1_full_webp_1teeaog from '@/assets/card/bowl/Bowl1-full.webp?url'
import _img_card_full_bowl_Bowl2_full_webp_zoje4x from '@/assets/card/bowl/Bowl2-full.webp?url'
import _img_card_full_bowl_Bowl3_full_webp_5yohle from '@/assets/card/bowl/Bowl3-full.webp?url'
import _img_card_full_bowl_Bowl4_full_webp_1b9xn0z from '@/assets/card/bowl/Bowl4-full.webp?url'
import _img_card_full_bowl_Bowl5_full_webp_hk2qhg from '@/assets/card/bowl/Bowl5-full.webp?url'
import _img_card_full_bowl_Bowl6_full_webp_1mvbvx1 from '@/assets/card/bowl/Bowl6-full.webp?url'
import _img_card_full_glasses_Glasses1_full_webp_1xp98ze from '@/assets/card/glasses/Glasses1-full.webp?url'
import _img_card_full_glasses_Glasses2_full_webp_13zecfv from '@/assets/card/glasses/Glasses2-full.webp?url'
import _img_card_full_glasses_Glasses3_full_webp_a9jfwc from '@/assets/card/glasses/Glasses3-full.webp?url'
import _img_card_full_glasses_Glasses4_full_webp_1fkslbx from '@/assets/card/glasses/Glasses4-full.webp?url'
import _img_card_full_glasses_Glasses5_full_webp_luxose from '@/assets/card/glasses/Glasses5-full.webp?url'
import _img_card_full_glasses_Glasses6_full_webp_1r66u7z from '@/assets/card/glasses/Glasses6-full.webp?url'

function image(
  src: string,
  width: number,
  height: number,
  fullSrc: string,
  fullWidth: number,
  fullHeight: number,
): ProjectImage {
  return { src, width, height, fullSrc, fullWidth, fullHeight }
}

export const _Freelance3dUrls: ProjectImage[] = [
  image(
    _img_freelance3d_00_preview_webp_1kk4wbz,
    1200,
    1200,
    _img_freelance3d_full_00_full_webp_1rxwob2,
    1280,
    1280,
  ),
  image(
    _img_freelance3d_01_preview_webp_1c750su,
    1200,
    1200,
    _img_freelance3d_full_01_full_webp_y81rrj,
    1200,
    1200,
  ),
  image(
    _img_freelance3d_02_preview_webp_13u559p,
    1200,
    1200,
    _img_freelance3d_full_02_full_webp_4i6v80,
    1200,
    1200,
  ),
  image(
    _img_freelance3d_03_preview_webp_vh59qk,
    1200,
    1200,
    _img_freelance3d_full_03_full_webp_19tg0nl,
    1200,
    1200,
  ),
  image(
    _img_freelance3d_04_preview_webp_n45e7f,
    1200,
    1200,
    _img_freelance3d_full_04_full_webp_g3l442,
    1200,
    1200,
  ),
  image(
    _img_freelance3d_05_preview_webp_er5ioa,
    1200,
    1438,
    _img_freelance3d_full_05_full_webp_1leu9jn,
    1505,
    1804,
  ),
  image(
    _img_freelance3d_06_preview_webp_6e5n55,
    1200,
    1127,
    _img_freelance3d_full_06_full_webp_rozd04,
    1536,
    1443,
  ),
  image(
    _img_freelance3d_07_preview_webp_1x29tl4,
    1200,
    965,
    _img_freelance3d_full_07_full_webp_1x08ifp,
    1478,
    1189,
  ),
  image(
    _img_freelance3d_08_preview_webp_1op9y1z,
    1200,
    863,
    _img_freelance3d_full_08_full_webp_13adlw6,
    1338,
    962,
  ),
  image(
    _img_freelance3d_09_preview_webp_1gca2iu,
    978,
    955,
    _img_freelance3d_full_09_full_webp_9kipcn,
    978,
    955,
  ),
  image(
    _img_freelance3d_10_preview_webp_agkws0,
    1200,
    859,
    _img_freelance3d_full_10_full_webp_1u2rd65,
    1324,
    948,
  ),
  image(
    _img_freelance3d_11_preview_webp_23l18v,
    833,
    593,
    _img_freelance3d_full_11_full_webp_10cwgmm,
    833,
    593,
  ),
  image(
    _img_freelance3d_12_preview_webp_1srp7ou,
    1200,
    1200,
    _img_freelance3d_full_12_full_webp_6n1k33,
    1280,
    1280,
  ),
  image(
    _img_freelance3d_13_preview_webp_1kepc5p,
    1200,
    1200,
    _img_freelance3d_full_13_full_webp_1byapio,
    1280,
    1280,
  ),
  image(
    _img_freelance3d_14_preview_webp_1c1pgmk,
    1200,
    1200,
    _img_freelance3d_full_14_full_webp_i8fsz5,
    1280,
    1280,
  ),
  image(
    _img_freelance3d_15_preview_webp_13opl3f,
    1200,
    1200,
    _img_freelance3d_full_15_full_webp_1njoyeq,
    1280,
    1280,
  ),
  image(
    _img_freelance3d_16_preview_webp_vbppka,
    1200,
    1200,
    _img_freelance3d_full_16_full_webp_ttu1v7,
    1200,
    1200,
  ),
  image(
    _img_freelance3d_17_preview_webp_mypu15,
    1200,
    1200,
    _img_freelance3d_full_17_full_webp_3z5bo,
    1200,
    1200,
  ),
]

export const _BirdsUrls: ProjectImage[] = [
  image(
    _img_wallpaper_birds_birds_preview_webp_yg55ka,
    1200,
    800,
    _img_wallpaper_full_birds_birds_full_webp_11m9f77,
    1920,
    1280,
  ),
]

export const _ChinoiserieUrls: ProjectImage[] = [
  image(
    _img_wallpaper_chinoiserie_chinoiserie1_preview_webp_o3r5vj,
    1200,
    1185,
    _img_wallpaper_full_chinoiserie_chinoiserie1_full_webp_1m68egu,
    2400,
    2370,
  ),
  image(
    _img_wallpaper_chinoiserie_chinoiserie2_preview_webp_fqrace,
    1200,
    800,
    _img_wallpaper_full_chinoiserie_chinoiserie2_full_webp_sgdhxb,
    2400,
    1600,
  ),
  image(
    _img_wallpaper_chinoiserie_chinoiserie3_preview_webp_7dret9,
    1200,
    945,
    _img_wallpaper_full_chinoiserie_chinoiserie3_full_webp_1xrmncw,
    2400,
    1890,
  ),
  image(
    _img_wallpaper_chinoiserie_chinoiserie4_preview_webp_1y1vl98,
    1200,
    733,
    _img_wallpaper_full_chinoiserie_chinoiserie4_full_webp_141rqtd,
    1280,
    782,
  ),
]

export const _ForestUrls: ProjectImage[] = [
  image(
    _img_wallpaper_forest_forest1_preview_webp_g81sfh,
    1200,
    814,
    _img_wallpaper_full_forest_forest1_full_webp_11iw47k,
    2400,
    1627,
  ),
  image(
    _img_wallpaper_forest_forest2_preview_webp_7v1wwc,
    700,
    420,
    _img_wallpaper_full_forest_forest2_full_webp_7t17o1,
    700,
    420,
  ),
  image(
    _img_wallpaper_forest_forest3_preview_webp_1yj63cb,
    1200,
    450,
    _img_wallpaper_full_forest_forest3_full_webp_1d4ad3m,
    2400,
    900,
  ),
  image(
    _img_wallpaper_forest_forest4_preview_webp_1q667t6,
    1200,
    993,
    _img_wallpaper_full_forest_forest4_full_webp_jefgk3,
    2400,
    1987,
  ),
]

export const _LlamaUnicornsUrls: ProjectImage[] = [
  image(
    _img_wallpaper_llamaUnicorns_llamaUnicorns1_preview_webp_u5tfjj,
    1200,
    1076,
    _img_wallpaper_full_llamaUnicorns_llamaUnicorns1_full_webp_1bwt1am,
    2400,
    2152,
  ),
  image(
    _img_wallpaper_llamaUnicorns_llamaUnicorns2_preview_webp_lstk0e,
    1200,
    800,
    _img_wallpaper_full_llamaUnicorns_llamaUnicorns2_full_webp_i6y4r3,
    2400,
    1600,
  ),
  image(
    _img_wallpaper_llamaUnicorns_llamaUnicorns3_preview_webp_dftoh9,
    1200,
    1029,
    _img_wallpaper_full_llamaUnicorns_llamaUnicorns3_full_webp_1ni7a6o,
    2400,
    2057,
  ),
]

export const _RoboUrls: ProjectImage[] = [
  image(
    _img_wallpaper_robo_robo1_preview_webp_2kb5xp,
    1200,
    900,
    _img_wallpaper_full_robo_robo1_full_webp_15zh12o,
    1448,
    1086,
  ),
  image(
    _img_wallpaper_robo_robo2_preview_webp_1t8fcdo,
    1200,
    2592,
    _img_wallpaper_full_robo_robo2_full_webp_c9m4j5,
    2400,
    5184,
  ),
]

export const _TropicalBirdsUrls: ProjectImage[] = [
  image(
    _img_wallpaper_tropicalBirds_tropicalBirds1_preview_webp_1ornq63,
    531,
    740,
    _img_wallpaper_full_tropicalBirds_tropicalBirds1_full_webp_18zv7ya,
    531,
    740,
  ),
  image(
    _img_wallpaper_tropicalBirds_tropicalBirds2_preview_webp_1genumy,
    1198,
    1313,
    _img_wallpaper_full_tropicalBirds_tropicalBirds2_full_webp_fa0ber,
    1198,
    1313,
  ),
  image(
    _img_wallpaper_tropicalBirds_tropicalBirds3_preview_webp_181nz3t,
    962,
    902,
    _img_wallpaper_full_tropicalBirds_tropicalBirds3_full_webp_1kl9guc,
    962,
    902,
  ),
  image(
    _img_wallpaper_tropicalBirds_tropicalBirds4_preview_webp_zoo3ko,
    836,
    901,
    _img_wallpaper_full_tropicalBirds_tropicalBirds4_full_webp_qvekat,
    836,
    901,
  ),
  image(
    _img_wallpaper_tropicalBirds_tropicalBirds5_preview_webp_rbo81j,
    952,
    903,
    _img_wallpaper_full_tropicalBirds_tropicalBirds5_full_webp_1w6npqe,
    952,
    903,
  ),
]

export const _TropicsUrls: ProjectImage[] = [
  image(
    _img_wallpaper_tropics_tropics1_preview_webp_1pc1nur,
    1200,
    900,
    _img_wallpaper_full_tropics_tropics1_full_webp_1ivtqgq,
    1448,
    1086,
  ),
  image(
    _img_wallpaper_tropics_tropics2_preview_webp_1gz1sbm,
    1200,
    469,
    _img_wallpaper_full_tropics_tropics2_full_webp_p5ytx7,
    2400,
    937,
  ),
]

export const _OtherProjectsArtUrls: ProjectImage[] = [
  image(
    _img_otherProjects_art_00_preview_webp_fuj01v,
    1200,
    1276,
    _img_otherProjects_full_art_00_full_webp_10wbewq,
    2400,
    2552,
  ),
  image(
    _img_otherProjects_art_01_preview_webp_7hj4iq,
    1200,
    1402,
    _img_otherProjects_full_art_01_full_webp_76gid7,
    2400,
    2805,
  ),
  image(
    _img_otherProjects_art_02_preview_webp_1y5nayp,
    1200,
    675,
    _img_otherProjects_full_art_02_full_webp_1chpnss,
    2400,
    1350,
  ),
  image(
    _img_otherProjects_art_03_preview_webp_1psnffk,
    1200,
    675,
    _img_otherProjects_full_art_03_full_webp_irur99,
    1920,
    1080,
  ),
  image(
    _img_otherProjects_art_04_preview_webp_1hfnjwf,
    1200,
    675,
    _img_otherProjects_full_art_04_full_webp_1o33wou,
    1920,
    1080,
  ),
  image(
    _img_otherProjects_art_05_preview_webp_192noda,
    1200,
    675,
    _img_otherProjects_full_art_05_full_webp_ud905b,
    1920,
    1080,
  ),
  image(
    _img_otherProjects_art_06_preview_webp_10pnsu5,
    1200,
    675,
    _img_otherProjects_full_art_06_full_webp_ne3ls,
    1920,
    1080,
  ),
  image(
    _img_otherProjects_art_07_preview_webp_scnxb0,
    1200,
    1662,
    _img_otherProjects_full_art_07_full_webp_15yn91d,
    1535,
    2126,
  ),
  image(
    _img_otherProjects_art_08_preview_webp_jzo1rv,
    1200,
    1800,
    _img_otherProjects_full_art_08_full_webp_c8schu,
    2400,
    3600,
  ),
  image(
    _img_otherProjects_art_09_preview_webp_bmo68q,
    1080,
    1694,
    _img_otherProjects_full_art_09_full_webp_1hk1hxf,
    1080,
    1694,
  ),
  image(
    _img_otherProjects_art_10_preview_webp_14s32h0,
    1000,
    1000,
    _img_otherProjects_full_art_10_full_webp_13163rt,
    1000,
    1000,
  ),
]

export const _OtherProjectsStudentWork3dMaxUrls: ProjectImage[] = [
  image(
    _img_otherProjects_studentWork_3dMax_____________preview_webp_16sc3nj,
    1200,
    813,
    _img_otherProjects_full_studentWork_3dMax_____________full_webp_9amxj2,
    2400,
    1626,
  ),
  image(
    _img_otherProjects_studentWork_3dMax________1_preview_webp_1jhbaac,
    1200,
    693,
    _img_otherProjects_full_studentWork_3dMax________1_full_webp_1arpzwp,
    2184,
    1262,
  ),
  image(
    _img_otherProjects_studentWork_3dMax________2_preview_webp_1b4ber7,
    1200,
    847,
    _img_otherProjects_full_studentWork_3dMax________2_full_webp_h1v3d6,
    1906,
    1346,
  ),
  image(
    _img_otherProjects_studentWork_3dMax____________________1_preview_webp_owk913,
    1200,
    771,
    _img_otherProjects_full_studentWork_3dMax____________________1_full_webp_1639ypy,
    1400,
    900,
  ),
  image(
    _img_otherProjects_studentWork_3dMax____________________2_preview_webp_gjkdhy,
    1200,
    771,
    _img_otherProjects_full_studentWork_3dMax____________________2_full_webp_cdf26f,
    1400,
    900,
  ),
  image(
    _img_otherProjects_studentWork_3dMax____________preview_webp_1koanl,
    1200,
    1200,
    _img_otherProjects_full_studentWork_3dMax____________full_webp_lcheks,
    2400,
    2400,
  ),
  image(
    _img_otherProjects_studentWork_3dMax______preview_webp_1mg1ui1,
    1200,
    771,
    _img_otherProjects_full_studentWork_3dMax______full_webp_1ce9jro,
    2400,
    1543,
  ),
  image(
    _img_otherProjects_studentWork_3dMax_______preview_webp_jpcsyz,
    1200,
    840,
    _img_otherProjects_full_studentWork_3dMax_______full_webp_12jdjma,
    2400,
    1680,
  ),
  image(
    _img_otherProjects_studentWork_3dMax______preview_webp_1i4fhp4,
    1200,
    841,
    _img_otherProjects_full_studentWork_3dMax______full_webp_1h6j479,
    2400,
    1681,
  ),
]

export const _OtherProjectsStudentWorkBlenderUrls: ProjectImage[] = [
  image(
    _img_otherProjects_studentWork_blender________preview_webp_seik6u,
    1200,
    1696,
    _img_otherProjects_full_studentWork_blender________full_webp_1jnokmf,
    2400,
    3392,
  ),
]

export const _OtherProjectsStudentWorkGraphicsUrls: ProjectImage[] = [
  image(
    _img_otherProjects_studentWork_graphics_1845_preview_webp_182qzwm,
    1200,
    1702,
    _img_otherProjects_full_studentWork_graphics_1845_full_webp_li774n,
    2400,
    3404,
  ),
  image(
    _img_otherProjects_studentWork_graphics_5ePDINeDxjI_preview_webp_1l9o7k1,
    1200,
    1626,
    _img_otherProjects_full_studentWork_graphics_5ePDINeDxjI_full_webp_ghpdbw,
    1594,
    2160,
  ),
  image(
    _img_otherProjects_studentWork_graphics_Bq7_ItMiucI_preview_webp_1u4nc4z,
    1200,
    1449,
    _img_otherProjects_full_studentWork_graphics_Bq7_ItMiucI_full_webp_5clw5m,
    1651,
    1994,
  ),
  image(
    _img_otherProjects_studentWork_graphics_cuFHlFBDWlw_preview_webp_hcyibi,
    1200,
    1258,
    _img_otherProjects_full_studentWork_graphics_cuFHlFBDWlw_full_webp_1iwz2zj,
    1663,
    1744,
  ),
  image(
    _img_otherProjects_studentWork_graphics_DRITAIkZYM8_preview_webp_1wk704c,
    1200,
    1608,
    _img_otherProjects_full_studentWork_graphics_DRITAIkZYM8_full_webp_ro0zgh,
    1612,
    2160,
  ),
  image(
    _img_otherProjects_studentWork_graphics_ej686d2CnQc_preview_webp_17md57a,
    1200,
    1646,
    _img_otherProjects_full_studentWork_graphics_ej686d2CnQc_full_webp_1cmhjt3,
    1575,
    2160,
  ),
  image(
    _img_otherProjects_studentWork_graphics_gFwlvPpdsv0_preview_webp_7hzgh1,
    960,
    1517,
    _img_otherProjects_full_studentWork_graphics_gFwlvPpdsv0_full_webp_1qzxys8,
    960,
    1517,
  ),
  image(
    _img_otherProjects_studentWork_graphics_nADpRxMnYnA_preview_webp_4kftu2,
    934,
    1251,
    _img_otherProjects_full_studentWork_graphics_nADpRxMnYnA_full_webp_1bj4loz,
    934,
    1251,
  ),
  image(
    _img_otherProjects_studentWork_graphics_rxTPjeELpkM_preview_webp_c4oyma,
    960,
    1295,
    _img_otherProjects_full_studentWork_graphics_rxTPjeELpkM_full_webp_hi1lcr,
    960,
    1295,
  ),
  image(
    _img_otherProjects_studentWork_graphics_uVCT4qGiaW0_preview_webp_boav3b,
    1200,
    1708,
    _img_otherProjects_full_studentWork_graphics_uVCT4qGiaW0_full_webp_vtwul2,
    1518,
    2160,
  ),
]

export const _OtherProjectsStudentWorkPaintingUrls: ProjectImage[] = [
  image(
    _img_otherProjects_studentWork_painting_1_preview_webp_15x9qjq,
    1200,
    1600,
    _img_otherProjects_full_studentWork_painting_1_full_webp_uka92v,
    2400,
    3200,
  ),
  image(
    _img_otherProjects_studentWork_painting_2_preview_webp_xk9v0l,
    1200,
    1600,
    _img_otherProjects_full_studentWork_painting_2_full_webp_ufcjc,
    2400,
    3200,
  ),
  image(
    _img_otherProjects_studentWork_painting_4_preview_webp_gua3yb,
    1200,
    1600,
    _img_otherProjects_full_studentWork_painting_4_full_webp_cftlfe,
    2400,
    3200,
  ),
  image(
    _img_otherProjects_studentWork_painting_6_preview_webp_4acw1,
    1200,
    1600,
    _img_otherProjects_full_studentWork_painting_6_full_webp_o17ubg,
    2400,
    3200,
  ),
  image(
    _img_otherProjects_studentWork_painting_7_preview_webp_1qsejc0,
    1200,
    1600,
    _img_otherProjects_full_studentWork_painting_7_full_webp_1tcgzr1,
    2400,
    3200,
  ),
  image(
    _img_otherProjects_studentWork_painting_8_preview_webp_1ifensv,
    1200,
    993,
    _img_otherProjects_full_studentWork_painting_8_full_webp_zmm37i,
    2400,
    1987,
  ),
  image(
    _img_otherProjects_studentWork_painting_9_preview_webp_1a2es9q,
    1200,
    993,
    _img_otherProjects_full_studentWork_painting_9_full_webp_5wr6nz,
    2400,
    1987,
  ),
]

export const _SignsOperatingModeUrls: ProjectImage[] = [
  image(
    _img_signs_operatingMode_1_1_preview_webp_1usz99i,
    960,
    1280,
    _img_signs_full_operatingMode_1_1_full_webp_1hk3wc7,
    960,
    1280,
  ),
  image(
    _img_signs_operatingMode_1_2_preview_webp_1mfzdqd,
    1200,
    929,
    _img_signs_full_operatingMode_1_2_full_webp_nu8zso,
    2400,
    1859,
  ),
  image(
    _img_signs_operatingMode_3_preview_webp_1b70rwn,
    960,
    1280,
    _img_signs_full_operatingMode_3_full_webp_zps3ue,
    960,
    1280,
  ),
  image(
    _img_signs_operatingMode_3_3_preview_webp_x72gte,
    1200,
    928,
    _img_signs_full_operatingMode_3_3_full_webp_1jg4ut7,
    2400,
    1856,
  ),
  image(
    _img_signs_operatingMode_4_1_preview_webp_15h3p6r,
    960,
    1280,
    _img_signs_full_operatingMode_4_1_full_webp_1301ypm,
    960,
    1280,
  ),
  image(
    _img_signs_operatingMode_4_2_preview_webp_x43tnm,
    1200,
    1054,
    _img_signs_full_operatingMode_4_2_full_webp_9a7263,
    2400,
    2108,
  ),
  image(
    _img_signs_operatingMode_image_2026_06_04_00_09_45_preview_webp_1pk6tif,
    1200,
    1178,
    _img_signs_full_operatingMode_image_2026_06_04_00_09_45_full_webp_nhmw2e,
    1224,
    1202,
  ),
  image(
    _img_signs_operatingMode_photo_2026_07_08_18_19_46__5__preview_webp_16xhige,
    960,
    1280,
    _img_signs_full_operatingMode_photo_2026_07_08_18_19_46__5__full_webp_18u0bjj,
    960,
    1280,
  ),
  image(
    _img_signs_operatingMode_photo_2026_07_08_18_19_47__3__preview_webp_1blupmz,
    960,
    1280,
    _img_signs_full_operatingMode_photo_2026_07_08_18_19_47__3__full_webp_1thv08i,
    960,
    1280,
  ),
  image(
    _img_signs_operatingMode_photo_2026_07_08_18_19_47_preview_webp_6z2zft,
    960,
    1280,
    _img_signs_full_operatingMode_photo_2026_07_08_18_19_47_full_webp_jkpq1g,
    960,
    1280,
  ),
]

export const _SignsQrUrls: ProjectImage[] = [
  image(
    _img_signs_qr_image_2026_06_03_12_33_50_preview_webp_13jqf51,
    1200,
    1065,
    _img_signs_full_qr_image_2026_06_03_12_33_50_full_webp_1411p3s,
    1728,
    1534,
  ),
  image(
    _img_signs_qr_photo_2026_07_08_18_19_47__2__preview_webp_q89he5,
    960,
    1280,
    _img_signs_full_qr_photo_2026_07_08_18_19_47__2__full_webp_1evx9gw,
    960,
    1280,
  ),
  image(
    _img_signs_qr_photo_2026_07_08_18_19_47__4__preview_webp_529k9b,
    960,
    1280,
    _img_signs_full_qr_photo_2026_07_08_18_19_47__4__full_webp_1j5mn72,
    960,
    1280,
  ),
]

export const _SignsSignsUrls: ProjectImage[] = [
  image(
    _img_signs_signs_2_1_preview_webp_m0imer,
    960,
    1280,
    _img_signs_full_signs_2_1_full_webp_gfloay,
    960,
    1280,
  ),
  image(
    _img_signs_signs_2_2_preview_webp_dniqvm,
    960,
    1280,
    _img_signs_full_signs_2_2_full_webp_1lqutqj,
    960,
    1280,
  ),
  image(
    _img_signs_signs_2_3_preview_webp_5aivch,
    955,
    576,
    _img_signs_full_signs_2_3_full_webp_s0zx70,
    955,
    576,
  ),
  image(
    _img_signs_signs_image_2026_05_29_13_13_09_preview_webp_58etbc,
    1176,
    1450,
    _img_signs_full_signs_image_2026_05_29_13_13_09_full_webp_eya0l1,
    1176,
    1450,
  ),
  image(
    _img_signs_signs_image_2026_06_03_16_41_18_preview_webp_gbeg2l,
    1200,
    1186,
    _img_signs_full_signs_image_2026_06_03_16_41_18_full_webp_1ajck2o,
    1368,
    1352,
  ),
  image(
    _img_signs_signs_image_2026_06_04_00_09_57_preview_webp_vywk4,
    1080,
    1188,
    _img_signs_full_signs_image_2026_06_04_00_09_57_full_webp_6pmkjt,
    1080,
    1188,
  ),
]

export const _CardBowlUrls: ProjectImage[] = [
  image(
    _img_card_bowl_Bowl1_preview_webp_m5fp4d,
    1200,
    1600,
    _img_card_full_bowl_Bowl1_full_webp_1teeaog,
    1800,
    2400,
  ),
  image(
    _img_card_bowl_Bowl2_preview_webp_dsftl8,
    1200,
    1600,
    _img_card_full_bowl_Bowl2_full_webp_zoje4x,
    1800,
    2400,
  ),
  image(
    _img_card_bowl_Bowl3_preview_webp_5ffy23,
    1200,
    1600,
    _img_card_full_bowl_Bowl3_full_webp_5yohle,
    1800,
    2400,
  ),
  image(
    _img_card_bowl_Bowl4_preview_webp_1w3k4i2,
    1200,
    1600,
    _img_card_full_bowl_Bowl4_full_webp_1b9xn0z,
    1800,
    2400,
  ),
  image(
    _img_card_bowl_Bowl5_preview_webp_1nqk8yx,
    1200,
    1600,
    _img_card_full_bowl_Bowl5_full_webp_hk2qhg,
    1800,
    2400,
  ),
  image(
    _img_card_bowl_Bowl6_preview_webp_1fdkdfs,
    1200,
    1600,
    _img_card_full_bowl_Bowl6_full_webp_1mvbvx1,
    1800,
    2400,
  ),
]

export const _CardGlassesUrls: ProjectImage[] = [
  image(
    _img_card_glasses_Glasses1_preview_webp_x6m8hv,
    1200,
    1600,
    _img_card_full_glasses_Glasses1_full_webp_1xp98ze,
    1800,
    2400,
  ),
  image(
    _img_card_glasses_Glasses2_preview_webp_otmcyq,
    1200,
    1600,
    _img_card_full_glasses_Glasses2_full_webp_13zecfv,
    1800,
    2400,
  ),
  image(
    _img_card_glasses_Glasses3_preview_webp_ggmhfl,
    1200,
    1600,
    _img_card_full_glasses_Glasses3_full_webp_a9jfwc,
    1800,
    2400,
  ),
  image(
    _img_card_glasses_Glasses4_preview_webp_83mlwg,
    1200,
    1600,
    _img_card_full_glasses_Glasses4_full_webp_1fkslbx,
    1800,
    2400,
  ),
  image(
    _img_card_glasses_Glasses5_preview_webp_1yrqscf,
    1200,
    1600,
    _img_card_full_glasses_Glasses5_full_webp_luxose,
    1800,
    2400,
  ),
  image(
    _img_card_glasses_Glasses6_preview_webp_1qeqwta,
    1200,
    1600,
    _img_card_full_glasses_Glasses6_full_webp_1r66u7z,
    1800,
    2400,
  ),
]
