// Auto-generated by scripts/update-image-dimensions.ts

import type { ProjectImage } from './portfolio'

const _freelanceModules = import.meta.glob('@/assets/freelance3d/*.{jpg,png,svg,gif,webp}', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>

const _freelanceDims: Record<string, { w: number; h: number }> = {
  '00.jpg': { w: 1280, h: 1280 },
  '01.jpg': { w: 1200, h: 1200 },
  '02.jpg': { w: 1200, h: 1200 },
  '03.jpg': { w: 1200, h: 1200 },
  '04.jpg': { w: 1200, h: 1200 },
  '05.jpg': { w: 1505, h: 1804 },
  '06.jpg': { w: 1536, h: 1443 },
  '07.jpg': { w: 1478, h: 1189 },
  '08.jpg': { w: 1338, h: 962 },
  '09.jpg': { w: 978, h: 955 },
  '10.jpg': { w: 1324, h: 948 },
  '11.jpg': { w: 833, h: 593 },
  '12.jpg': { w: 1280, h: 1280 },
  '13.jpg': { w: 1280, h: 1280 },
  '14.jpg': { w: 1280, h: 1280 },
  '15.jpg': { w: 1280, h: 1280 },
  '16.jpg': { w: 1200, h: 1200 },
  '17.jpg': { w: 1200, h: 1200 },
}

const _wallpaperModules = import.meta.glob('@/assets/wallpaper/**/*.{jpg,png,svg,gif,webp}', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>

const _wallpaperDims: Record<string, { w: number; h: number }> = {
  'birds/birds.jpg': { w: 1920, h: 1280 },
  'chinoiserie/chinoiserie1.jpg': { w: 3190, h: 3150 },
  'chinoiserie/chinoiserie2.jpg': { w: 4000, h: 2666 },
  'chinoiserie/chinoiserie3.jpg': { w: 2835, h: 2232 },
  'chinoiserie/chinoiserie4.jpg': { w: 1280, h: 782 },
  'forest/forest1.jpg': { w: 5906, h: 4005 },
  'forest/forest2.jpg': { w: 700, h: 420 },
  'forest/forest3.jpg': { w: 5906, h: 2215 },
  'forest/forest4.jpg': { w: 3300, h: 2732 },
  'llamaUnicorns/llamaUnicorns1.jpg': { w: 3011, h: 2700 },
  'llamaUnicorns/llamaUnicorns2.jpg': { w: 3000, h: 2000 },
  'llamaUnicorns/llamaUnicorns3.jpg': { w: 2835, h: 2430 },
  'robo/robo1.png': { w: 1448, h: 1086 },
  'robo/robo2.jpg': { w: 2734, h: 5906 },
  'tropicalBirds/tropicalBirds1.jpg': { w: 531, h: 740 },
  'tropicalBirds/tropicalBirds2.png': { w: 1198, h: 1313 },
  'tropicalBirds/tropicalBirds3.jpg': { w: 962, h: 902 },
  'tropicalBirds/tropicalBirds4.jpg': { w: 836, h: 901 },
  'tropicalBirds/tropicalBirds5.jpg': { w: 952, h: 903 },
  'tropics/tropics1.png': { w: 1448, h: 1086 },
  'tropics/tropics2.jpg': { w: 5906, h: 2307 },
}

export const _Freelance3dUrls: ProjectImage[] = Object.entries(_freelanceModules)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([fp, src]) => {
    const f = fp.split('/').pop() ?? ''
    const d = _freelanceDims[f] ?? { w: 0, h: 0 }
    return { src, width: d.w, height: d.h }
  })

export const _BirdsUrls: ProjectImage[] = []

export const _ChinoiserieUrls: ProjectImage[] = []

export const _ForestUrls: ProjectImage[] = []

export const _LlamaUnicornsUrls: ProjectImage[] = []

export const _RoboUrls: ProjectImage[] = []

export const _TropicalBirdsUrls: ProjectImage[] = []

export const _TropicsUrls: ProjectImage[] = []

for (const [fp, src] of Object.entries(_wallpaperModules)) {
  const m = fp.match(/wallpaper\/([^/]+)\/(.+)$/)
  if (m) {
    const key = m[1] + '/' + m[2]
    const d = _wallpaperDims[key] ?? { w: 0, h: 0 }
    const img: ProjectImage = { src, width: d.w, height: d.h }
    switch (m[1]) {
      case 'birds':
        _BirdsUrls.push(img)
        break
      case 'chinoiserie':
        _ChinoiserieUrls.push(img)
        break
      case 'forest':
        _ForestUrls.push(img)
        break
      case 'llamaUnicorns':
        _LlamaUnicornsUrls.push(img)
        break
      case 'robo':
        _RoboUrls.push(img)
        break
      case 'tropicalBirds':
        _TropicalBirdsUrls.push(img)
        break
      case 'tropics':
        _TropicsUrls.push(img)
        break
    }
  }
}

// sort all wallpaper arrays
_BirdsUrls.sort((a, b) => a.src.localeCompare(b.src))
_ChinoiserieUrls.sort((a, b) => a.src.localeCompare(b.src))
_ForestUrls.sort((a, b) => a.src.localeCompare(b.src))
_LlamaUnicornsUrls.sort((a, b) => a.src.localeCompare(b.src))
_RoboUrls.sort((a, b) => a.src.localeCompare(b.src))
_TropicalBirdsUrls.sort((a, b) => a.src.localeCompare(b.src))
_TropicsUrls.sort((a, b) => a.src.localeCompare(b.src))
